import type { Metadata } from "next";
import { Blocks, CheckCircle2, FileCheck2, Gauge, Layers3, Languages, RotateCcw, Volume2, WifiOff } from "lucide-react";
import { ClosingCta } from "@/components/site/closing-cta";
import { FaqSection } from "@/components/site/faq-section";
import { PageHero } from "@/components/site/page-hero";
import { PageShell } from "@/components/site/page-shell";
import { VectorScene } from "@/components/site/vector-scene";
import { Badge } from "@/components/ui/badge";
import { Card, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";

export const metadata: Metadata={title:"Features — Litera",description:"Explore Litera's accessible publishing workflow."};
const features=[[Blocks,"Block-based storyboard","Edit meaningful content units without losing semantic structure."],[Layers3,"Source fidelity","Keep every generated section connected to its source pages."],[Volume2,"Entity-level speech","Review and regenerate one narratable item without repeating the whole book."],[Languages,"Swahili-first review","Store pronunciation decisions separately from visible source text."],[Gauge,"Live quality checks","See coverage, narration, accessibility and responsive readiness together."],[RotateCcw,"Reversible editing","Preserve versions and restore earlier page states safely."],[FileCheck2,"Validated release","Block publication when required evidence or assets are missing."],[WifiOff,"Offline output","Produce complete packages for low-connectivity learning environments."]] as const;
export default function FeaturesPage(){return <PageShell><main>
  <PageHero eyebrow="Product capabilities" title="Powerful where it matters. Calm everywhere else." description="Litera brings the difficult parts of inclusive publishing into a focused workflow with clear progress and safe recovery." icon={Layers3}/>
  <section className="mx-auto grid max-w-7xl gap-14 px-5 py-24 lg:grid-cols-2 lg:items-center lg:px-8" data-reveal><div><Badge variant="secondary">Visual by design</Badge><h2 className="mt-5 text-4xl font-semibold tracking-tight">See the publication, not its machinery.</h2><p className="mt-5 leading-8 text-muted-foreground">Move, refine and review meaningful content blocks on a responsive canvas. Litera keeps the underlying structure reliable while the team concentrates on teaching.</p><ul className="mt-8 grid gap-3">{["Responsive page preview","Semantic content blocks","Source-to-output traceability"].map(item=><li className="flex items-center gap-3" key={item}><CheckCircle2 className="size-5 text-primary"/>{item}</li>)}</ul></div><VectorScene/></section>
  <section className="border-y bg-muted/30" data-reveal><div className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><div className="mb-12 max-w-2xl"><p className="text-sm font-semibold uppercase tracking-[.2em] text-primary">Everything connected</p><h2 className="mt-4 text-4xl font-semibold tracking-tight">A complete publishing toolkit.</h2></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{features.map(([Icon,title,text])=><Card className="motion-card" key={title}><CardHeader className="p-7"><Icon className="size-6 text-primary"/><CardTitle className="pt-5 text-lg">{title}</CardTitle><CardDescription className="leading-7">{text}</CardDescription></CardHeader></Card>)}</div></div></section>
  <section id="workflow" className="mx-auto max-w-7xl px-5 py-24 lg:px-8" data-reveal><div className="grid gap-12 lg:grid-cols-[.75fr_1.25fr]"><div><Badge variant="outline">Workflow intelligence</Badge><h2 className="mt-5 text-4xl font-semibold tracking-tight">Progress that explains itself.</h2><p className="mt-5 leading-8 text-muted-foreground">Every stage has a clear owner, visible evidence and an understandable next action.</p></div><div className="grid gap-px overflow-hidden rounded-2xl border bg-border sm:grid-cols-2">{[["Import","Understand pages and assets"],["Compose","Create a responsive lesson"],["Review","Resolve speech and access"],["Release","Publish a validated version"]].map(([title,text],i)=><div className="bg-background p-7" key={title}><span className="font-mono text-xs text-primary">0{i+1}</span><h3 className="mt-10 text-xl font-semibold">{title}</h3><p className="mt-2 text-sm text-muted-foreground">{text}</p></div>)}</div></div></section>
  <section id="narration" className="border-y bg-muted/30" data-reveal><div className="mx-auto grid max-w-7xl gap-14 px-5 py-24 lg:grid-cols-2 lg:items-center lg:px-8"><VectorScene variant="listen"/><div><Badge variant="secondary">Language-aware audio</Badge><h2 className="mt-5 text-4xl font-semibold tracking-tight">Narration becomes a reviewable editorial layer.</h2><p className="mt-5 leading-8 text-muted-foreground">Listen sentence by sentence, preserve pronunciation decisions and regenerate only the audio that changed. Reviewers remain in control of meaning and quality.</p></div></div></section>
  <FaqSection title="Feature questions, made simple." items={[["Can source content remain traceable?","Each authored element can retain its relationship to the original page or object, supporting review and safe revision."],["What happens when a page changes?","Changes are versioned and affected narration or checks can be revisited without rebuilding unrelated work."],["Can releases be blocked?","Yes. Required evidence, accessibility alternatives and narration approvals can become explicit release gates."],["Is the output responsive?","The authoring model is designed for content that reflows across phones, tablets and larger displays."]]}/>
  <ClosingCta title="Bring your next publication into one clear workflow." description="Start with a source, shape the learning experience and keep every decision visible from import to release."/>
</main></PageShell>}
