import type { Metadata } from "next";
import { Accessibility, AudioLines, CheckCircle2, Keyboard, ScanText, Smartphone, Waypoints } from "lucide-react";
import { ClosingCta } from "@/components/site/closing-cta";
import { FaqSection } from "@/components/site/faq-section";
import { PageHero } from "@/components/site/page-hero";
import { PageShell } from "@/components/site/page-shell";
import { VectorScene } from "@/components/site/vector-scene";
import { Card, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";

export const metadata: Metadata = { title: "Accessibility — Litera", description: "How Litera supports inclusive authoring and output." };
const commitments = [[Keyboard,"Keyboard complete","Every authoring action has a non-pointer route."],[ScanText,"Semantic by default","Headings, landmarks and reading order stay explicit."],[AudioLines,"Meaningful narration","Descriptions and spoken text remain reviewable in context."],[Smartphone,"Reflow that works","Content remains usable on phones, tablets and large displays."],[Waypoints,"Visible quality gates","Missing alternatives and broken associations block release."]] as const;

export default function AccessibilityPage() { return <PageShell><main>
  <PageHero eyebrow="Accessibility" title="Inclusion is part of the publishing model." description="Litera targets WCAG 2.2 AA for its workspace and treats accessible learner output as a release requirement." icon={Accessibility}/>
  <section id="standards" className="mx-auto max-w-7xl px-5 py-24 lg:px-8" data-reveal><div className="mb-10 max-w-2xl"><h2 className="text-4xl font-semibold tracking-tight">Designed for authors and learners.</h2><p className="mt-4 leading-7 text-muted-foreground">Accessible output starts with an authoring experience that makes structure, language, narration and alternatives easy to understand.</p></div><div className="grid gap-4 md:grid-cols-2">{commitments.map(([Icon,title,text])=><Card className="motion-card" key={title}><CardHeader className="p-7"><Icon className="size-6 text-primary"/><CardTitle className="pt-4">{title}</CardTitle><CardDescription className="leading-7">{text}</CardDescription></CardHeader></Card>)}</div></section>
  <section className="border-y bg-muted/30" data-reveal><div className="mx-auto grid max-w-7xl gap-14 px-5 py-24 lg:grid-cols-2 lg:items-center lg:px-8"><VectorScene variant="review"/><div><p className="text-sm font-semibold uppercase tracking-[.2em] text-primary">Authoring with awareness</p><h2 className="mt-4 text-4xl font-semibold tracking-tight">Fix barriers while the work is still fluid.</h2><p className="mt-5 leading-8 text-muted-foreground">The workspace makes reading order, alternatives, language and interaction status visible beside the content. Guidance arrives where teams can act on it, not in a report after release.</p></div></div></section>
  <section className="mx-auto max-w-7xl px-5 py-24 lg:px-8" data-reveal><div className="grid gap-12 lg:grid-cols-2"><div><p className="text-sm font-semibold uppercase tracking-[.2em] text-primary">Release confidence</p><h2 className="mt-4 text-4xl font-semibold tracking-tight">Quality is visible before publishing.</h2><p className="mt-4 leading-7 text-muted-foreground">Teams see actionable checks in the same context where they write and review, reducing late surprises.</p></div><ul className="grid gap-4">{["Reading order and heading structure","Text alternatives for meaningful media","Narration status by language","Keyboard and responsive presentation"].map(item=><li className="flex items-center gap-3 rounded-xl border bg-background p-4" key={item}><CheckCircle2 className="size-5 shrink-0 text-primary"/><span className="font-medium">{item}</span></li>)}</ul></div></section>
  <section className="border-y bg-muted/30" data-reveal><div className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><div className="grid gap-6 md:grid-cols-3">{[["Perceivable","Text, media and narration offer meaningful alternatives."],["Operable","Keyboard routes and clear focus support different ways of working."],["Understandable","Consistent language and feedback reduce cognitive effort."]].map(([title,text],i)=><div className="rounded-2xl border bg-background p-7" key={title}><span className="font-mono text-xs text-primary">0{i+1}</span><h3 className="mt-10 text-xl font-semibold">{title}</h3><p className="mt-3 text-sm leading-7 text-muted-foreground">{text}</p></div>)}</div></div></section>
  <FaqSection title="Accessibility questions, answered." items={[["Does Litera guarantee conformance automatically?","No automated system can replace expert and user review. Litera makes requirements visible, catches common issues and supports evidence-based human approval."],["Is keyboard access considered in the workspace?","Yes. Authoring actions are designed to have non-pointer routes and visible focus behaviour."],["How are images handled?","Meaningful media can carry reviewable text alternatives, while decorative elements can be identified appropriately."],["What about smaller screens?","Content is designed to reflow and remain usable across phones, tablets and larger displays."],["Can accessibility block a release?","Required alternatives, associations and other quality evidence can be configured as visible release gates."]]}/>
  <ClosingCta title="Make inclusive quality part of every publishing decision." description="Create, review and release learning experiences with accessibility visible from the beginning."/>
</main></PageShell> }
