"use client";

import { Accessibility, AudioLines, CheckCircle2, FileText, FileUp, ImageIcon, Languages, ListChecks, PanelTop, Play, ShieldCheck, UploadCloud, Volume2 } from "lucide-react";
import { useEffect, useState } from "react";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";

const stages=[
  {value:"import",label:"Import",icon:FileUp,title:"Bring the source into focus",text:"Litera maps pages, media and structure into a clear starting point for the whole team."},
  {value:"storyboard",label:"Storyboard",icon:PanelTop,title:"Shape the lesson visually",text:"Arrange meaningful blocks on a responsive canvas while structure stays protected."},
  {value:"narrate",label:"Narrate",icon:AudioLines,title:"Review Swahili in context",text:"Listen sentence by sentence, refine pronunciation and regenerate only what changed."},
  {value:"verify",label:"Verify",icon:Accessibility,title:"Release with visible evidence",text:"Resolve accessibility, language and quality gates before creating a validated release."},
] as const;
type Stage=typeof stages[number]["value"];

export function ProductWalkthrough(){
  const[active,setActive]=useState<Stage>("import");
  useEffect(()=>{const timer=window.setInterval(()=>setActive(current=>stages[(stages.findIndex(stage=>stage.value===current)+1)%stages.length].value),5000);return()=>window.clearInterval(timer)},[]);
  return <section id="workflow" className="border-y bg-muted/30" data-reveal><div className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><Badge variant="outline" className="bg-background">See Litera in motion</Badge><h2 className="mt-5 max-w-3xl text-4xl font-semibold tracking-[-0.04em] sm:text-5xl">One publication. Four connected stages.</h2><p className="mt-5 max-w-2xl leading-7 text-muted-foreground">Follow the work from source material to an accessible, narrated release.</p><Tabs className="mt-10" onValueChange={value=>setActive(value as Stage)} value={active}><div className="max-w-full overflow-x-auto"><TabsList className="h-auto w-max justify-start gap-0 rounded-none border-b bg-transparent p-0">{stages.map((stage,index)=><TabsTrigger className="walkthrough-tab h-12 min-w-32 rounded-none bg-transparent px-5 shadow-none data-[state=active]:bg-transparent data-[state=active]:text-primary data-[state=active]:shadow-none" key={stage.value} value={stage.value}><span className="font-mono text-[10px] text-muted-foreground">0{index+1}</span>{stage.label}</TabsTrigger>)}</TabsList></div>{stages.map(stage=><TabsContent className="walkthrough-panel mt-10" key={stage.value} value={stage.value}><div className="grid gap-12 lg:grid-cols-[.7fr_1.3fr] lg:items-center"><div className="walkthrough-copy"><span className="grid size-11 place-items-center rounded-xl bg-primary/10 text-primary"><stage.icon className="size-5"/></span><h3 className="mt-6 text-3xl font-semibold tracking-tight">{stage.title}</h3><p className="mt-4 max-w-lg leading-7 text-muted-foreground">{stage.text}</p></div><ProductScreen stage={stage.value}/></div></TabsContent>)}</Tabs></div></section>
}

function ProductScreen({stage}:{stage:Stage}){return <div className="walkthrough-visual relative rounded-[2rem] border bg-background p-3 shadow-2xl shadow-primary/10"><div className="overflow-hidden rounded-[1.4rem] border bg-background"><WindowBar stage={stage}/>{stage==="import"?<ImportScene/>:stage==="storyboard"?<StoryboardScene/>:stage==="narrate"?<NarrationScene/>:<VerificationScene/>}</div><CollaborativeCursor stage={stage}/></div>}

function WindowBar({stage}:{stage:Stage}){const labels={import:"Source import",storyboard:"Visual storyboard",narrate:"Swahili narration",verify:"Release centre"};return <div className="flex h-11 items-center justify-between border-b px-4"><div className="flex gap-1.5"><i className="size-2 rounded-full bg-border"/><i className="size-2 rounded-full bg-border"/><i className="size-2 rounded-full bg-primary"/></div><span className="text-[10px] font-semibold text-muted-foreground">Litera · {labels[stage]}</span><Badge variant="secondary">Live</Badge></div>}

function ImportScene(){return <div className="min-h-80 bg-muted/20 p-4"><div className="grid min-h-72 overflow-hidden rounded-xl border bg-background sm:grid-cols-[1.2fr_.8fr]"><div className="grid place-items-center border-b p-5 sm:border-b-0 sm:border-e"><div className="grid min-h-52 w-full place-items-center rounded-xl border border-dashed border-primary/35 bg-primary/[.04] text-center"><div><span className="mx-auto grid size-12 place-items-center rounded-full bg-primary/10 text-primary"><UploadCloud className="size-5"/></span><p className="mt-4 text-sm font-semibold">Drop a source book here</p><p className="mt-1 text-[9px] text-muted-foreground">PDF, EPUB or structured package</p><Badge className="mt-4" variant="outline">Browse source files</Badge></div></div></div><div className="flex flex-col p-4"><div><p className="text-xs font-semibold">Source detected</p><p className="mt-1 text-[9px] text-muted-foreground">Mazingira-yetu.pdf · 18.4 MB</p></div><div className="mt-4 grid gap-2">{[[FileText,"Pages mapped","48"],[ImageIcon,"Images found","32"],[Languages,"Languages","2"]].map(([Icon,label,value])=>{const ItemIcon=Icon as typeof FileText;return <div className="flex items-center gap-3 rounded-lg border p-3" key={String(label)}><span className="grid size-8 place-items-center rounded-lg bg-primary/10 text-primary"><ItemIcon className="size-3.5"/></span><div className="min-w-0 flex-1"><p className="text-[8px] text-muted-foreground">{String(label)}</p><p className="text-[10px] font-semibold">{String(value)}</p></div><CheckCircle2 className="size-3.5 text-primary"/></div>})}</div><div className="mt-auto pt-4"><div className="mb-2 flex justify-between text-[9px]"><span>Mapping source objects</span><span className="text-primary">72%</span></div><Progress value={72}/></div></div></div></div>}

function StoryboardScene(){return <div className="grid min-h-80 grid-cols-[6.5rem_1fr_7.5rem]"><aside className="border-e bg-muted/40 p-3"><p className="text-[8px] font-semibold uppercase text-muted-foreground">Pages</p>{["Jalada","Utangulizi","Somo 01","Mazoezi"].map((item,index)=><div className={`mt-2 rounded-lg px-2 py-2 text-[9px] ${index===2?"bg-primary text-primary-foreground":"bg-background text-muted-foreground"}`} key={item}>{item}</div>)}</aside><div className="bg-muted/20 p-3"><div className="h-full w-full rounded-xl border bg-background p-3 shadow-sm"><div className="rounded-lg border p-3"><p className="text-[8px] text-muted-foreground">Heading</p><p className="mt-2 text-sm font-semibold">Mazingira yetu</p></div><div className="mt-2 grid min-h-36 place-items-center rounded-lg bg-primary/10"><ImageIcon className="size-7 text-primary"/></div><div className="mt-2 grid grid-cols-2 gap-2"><span className="h-14 rounded-lg border bg-muted/30"/><span className="h-14 rounded-lg border bg-muted/30"/></div></div></div><aside className="border-s p-3"><p className="text-[8px] font-semibold uppercase text-muted-foreground">Blocks</p>{[[PanelTop,"Section"],[FileText,"Text"],[ImageIcon,"Media"],[ListChecks,"Activity"]].map(([Icon,label])=>{const ItemIcon=Icon as typeof PanelTop;return <div className="mt-2 flex items-center gap-2 rounded-lg border p-2 text-[8px]" key={String(label)}><ItemIcon className="size-3 text-primary"/>{String(label)}</div>})}</aside></div>}

function NarrationScene(){return <div className="min-h-80 p-5"><div className="grid gap-4 sm:grid-cols-[1.15fr_.85fr]"><div className="rounded-2xl border p-4"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-full bg-primary text-primary-foreground"><Play className="size-4 fill-current"/></span><div><p className="text-xs font-semibold">Mazingira yetu</p><p className="text-[9px] text-muted-foreground">Kiswahili · Tanzania</p></div></div><div className="mt-7 flex h-20 items-center gap-1">{[3,7,5,10,14,8,17,12,6,15,9,4,11,16,7,3,12,8,5,10].map((height,index)=><i className="narration-wave flex-1 rounded-full bg-primary/70" style={{height:`${height*3}px`,animationDelay:`${index*45}ms`}} key={`${height}-${index}`}/>)}</div><div className="mt-5 flex justify-between text-[9px] text-muted-foreground"><span>00:08</span><span>00:18</span></div></div><div className="flex flex-col gap-3"><div className="rounded-xl border p-3"><div className="flex items-center gap-2"><Volume2 className="size-4 text-primary"/><p className="text-[10px] font-semibold">Pronunciation</p></div><p className="mt-3 rounded-lg bg-muted/50 p-2 text-[9px]">mazingira · ma-zi-NGI-ra</p></div>{["Natural pace","Sentence approved","Voice: Neema"].map(item=><div className="flex items-center gap-2 rounded-xl border p-3 text-[9px]" key={item}><CheckCircle2 className="size-3.5 text-primary"/>{item}</div>)}</div></div></div>}

function VerificationScene(){return <div className="min-h-80 p-5"><div className="grid gap-4 sm:grid-cols-[.8fr_1.2fr]"><div className="rounded-2xl bg-primary/10 p-5"><ShieldCheck className="size-8 text-primary"/><p className="mt-7 text-3xl font-semibold">94%</p><p className="mt-1 text-[9px] text-muted-foreground">Release readiness</p><Progress className="mt-5" value={94}/></div><div className="flex flex-col gap-2">{[["Page structure","Complete"],["Text alternatives","Complete"],["Swahili narration","Complete"],["Keyboard routes","Complete"],["Final stakeholder approval","Waiting"]].map(([label,status],index)=><div className="flex items-center justify-between rounded-xl border p-3" key={label}><div className="flex items-center gap-2"><span className={`grid size-6 place-items-center rounded-full ${index<4?"bg-primary/10 text-primary":"bg-muted text-muted-foreground"}`}>{index<4?<CheckCircle2 className="size-3.5"/>:<ListChecks className="size-3.5"/>}</span><span className="text-[9px] font-medium">{label}</span></div><Badge variant={index<4?"secondary":"outline"}>{status}</Badge></div>)}</div></div></div>}

function CollaborativeCursor({stage}:{stage:Stage}){const positions={import:"left-[56%] top-[42%]",storyboard:"left-[62%] top-[52%]",narrate:"left-[48%] top-[58%]",verify:"left-[72%] top-[48%]"};return <div className={`canva-cursor absolute ${positions[stage]}`} aria-hidden="true"><svg className="size-7 drop-shadow" viewBox="0 0 28 28"><path d="M4 2.5 23 15l-8.6 1.8-4.8 7.4L4 2.5Z" fill="#df301c" stroke="white" strokeWidth="2"/></svg><span className="absolute left-5 top-5 rounded-full bg-primary px-2 py-1 text-[9px] font-semibold text-primary-foreground shadow">Amina</span></div>}
