"use client";
import { CornerUpRight, GripVertical, ListPlus, Trash2 } from "lucide-react";
import { useState } from "react";
import type { DeviceBook } from "@/components/device/device-types";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { toast } from "@/lib/feedback";
type Prompt = NonNullable<DeviceBook["correctionPrompts"]>[number];
export function BookPromptQueue({ disabled, prompts, onChange }: { disabled: boolean; prompts: Prompt[]; onChange: (prompts: Prompt[]) => Promise<void> }) {
  const [text, setText] = useState(""); const [dragged, setDragged] = useState<string>();
  async function add() { const value = text.trim(); if (!value) return; await onChange([...prompts, { id: crypto.randomUUID(), text: value, status: prompts.length ? "queued" : "next", createdAt: new Date().toISOString() }]); setText(""); toast.success("Correction prompt added to the queue."); }
  async function steer(id: string) { const selected = prompts.find(item => item.id === id); if (!selected) return; await onChange([{ ...selected, status: "next" }, ...prompts.filter(item => item.id !== id).map(item => ({ ...item, status: "queued" as const }))]); toast.success("Prompt steered to run next."); }
  async function reorder(targetId: string) { if (!dragged || dragged === targetId) return; const next = [...prompts]; const from = next.findIndex(item => item.id === dragged); const to = next.findIndex(item => item.id === targetId); const [item] = next.splice(from, 1); next.splice(to, 0, item); await onChange(next.map((prompt, index) => ({ ...prompt, status: index === 0 ? "next" : "queued" }))); setDragged(undefined); }
  return <div className="grid gap-4 rounded-2xl border bg-muted/20 p-5"><div><h3 className="font-semibold">Correction prompt queue</h3><p className="mt-1 text-sm text-muted-foreground">Queue edits, steer an urgent instruction to the front, or drag prompts into a new order.</p></div><div className="flex flex-col gap-2 sm:flex-row"><Textarea className="min-h-20 flex-1" disabled={disabled} onChange={event => setText(event.target.value)} onKeyDown={event => { if ((event.metaKey || event.ctrlKey) && event.key === "Enter") void add(); }} placeholder="Describe the correction Litera should make at this stage…" value={text}/><Button className="sm:self-end" disabled={disabled || !text.trim()} onClick={() => void add()}><ListPlus data-icon="inline-start"/>Queue prompt</Button></div>{prompts.length ? <ol className="grid gap-2">{prompts.map((prompt, index) => <li className="flex items-start gap-3 rounded-xl border bg-background p-3 transition-colors duration-400 hover:border-primary/30" draggable key={prompt.id} onDragStart={() => setDragged(prompt.id)} onDragOver={event => event.preventDefault()} onDrop={() => void reorder(prompt.id)}><GripVertical className="mt-1 size-4 shrink-0 cursor-grab text-muted-foreground"/><span className="mt-0.5 text-xs font-semibold text-primary">{String(index + 1).padStart(2, "0")}</span><p className="min-w-0 flex-1 whitespace-pre-wrap text-sm leading-6">{prompt.text}</p><span className="rounded-full bg-primary/10 px-2 py-1 text-[10px] font-semibold uppercase text-primary">{index === 0 ? "Next" : "Queued"}</span><Button aria-label="Run this prompt next" onClick={() => void steer(prompt.id)} size="icon-sm" title="Steer to front" variant="ghost"><CornerUpRight/></Button><Button aria-label="Remove prompt" onClick={() => void onChange(prompts.filter(item => item.id !== prompt.id))} size="icon-sm" title="Remove" variant="ghost"><Trash2/></Button></li>)}</ol> : <p className="text-sm text-muted-foreground">No correction prompts queued for this book.</p>}</div>;
}
