"use client";

import { ArrowLeft, ArrowRight, BookOpen, Check, CheckCircle2, FileText, FileUp, HelpCircle, KeyRound, Layers3, Maximize2, Minus, MousePointer2, Play, RefreshCw, ShieldCheck, UploadCloud, Video, X } from "lucide-react";
import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { Carousel, type CarouselApi, CarouselContent, CarouselItem, CarouselNext, CarouselPrevious } from "@/components/ui/carousel";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { cn } from "@/lib/utils";

const onboardingKey = "litera-onboarding-complete-v1";
const slides = [
  { eyebrow: "Private by design", title: "Your publishing library, on your device", description: "Every source, draft, and finished project stays in Litera’s local application storage—without an account or cloud library.", icon: BookOpen, points: ["Local book history", "One workspace per publication"] },
  { eyebrow: "A calmer workflow", title: "One clear path from source to release", description: "Move through extraction, structure, storyboard, image captioning, easy read, language, speech, signed video, validation, and export at your own pace.", icon: Layers3, points: ["Ten focused stages", "Return to any stage"] },
  { eyebrow: "Continue existing work", title: "Pick up exactly where you left off", description: "Open PDF, EPUB, Web Publication, ZIP, and compatible project packages to correct only the stage that needs attention.", icon: FileUp, points: ["Reimport project packages", "Preserve completed work"] },
  { eyebrow: "Your choice of intelligence", title: "Connect the AI providers you trust", description: "Configure only the providers you choose. Their keys are encrypted locally and never synchronized to a Litera account.", icon: KeyRound, points: ["OpenAI, Gemini, Anthropic", "Encrypted provider vault"] },
  { eyebrow: "Always in control", title: "Review every detail before release", description: "Visible progress, quality checks, and editable stages keep automated work inspectable, correctable, and reversible.", icon: ShieldCheck, points: ["Clear completion status", "Review before export"] },
] as const;

export function DeviceOnboarding({ open, onOpenChange }: { open: boolean; onOpenChange: (open: boolean) => void }) {
  const [api, setApi] = useState<CarouselApi>();
  const [current, setCurrent] = useState(0);
  useEffect(() => { if (!api) return; const update = () => setCurrent(api.selectedScrollSnap()); const frame = window.requestAnimationFrame(update); api.on("select", update); return () => { window.cancelAnimationFrame(frame); api.off("select", update); }; }, [api]);
  function finish() { localStorage.setItem(onboardingKey, "true"); onOpenChange(false); }
  return <Dialog onOpenChange={onOpenChange} open={open}><DialogContent className="max-h-[calc(100dvh-2rem)] w-[calc(100vw-2rem)] overflow-y-auto overflow-x-hidden rounded-3xl p-0 sm:!max-w-6xl" showCloseButton={false}><DialogHeader className="sr-only"><DialogTitle>Welcome to Litera</DialogTitle><DialogDescription>A five-step introduction to the local publishing workspace.</DialogDescription></DialogHeader>
    <div className="flex items-center justify-between border-b px-6 py-4 sm:px-9"><span className="text-sm font-medium text-muted-foreground">A quick introduction</span><Button onClick={finish} size="sm" variant="ghost">Skip</Button></div>
    <Carousel className="min-w-0 px-5 py-5 sm:px-8 sm:py-6 lg:px-9 lg:py-8" opts={{ watchDrag: true }} setApi={setApi}><CarouselContent>{slides.map((slide, index) => <CarouselItem key={slide.title}><div className="grid w-full min-w-0 gap-5 sm:gap-7 lg:min-h-[min(31rem,calc(100dvh-13rem))] lg:grid-cols-2 lg:items-stretch">
      <div className="flex min-w-0 flex-col justify-center py-2 lg:px-3"><span className="w-fit rounded-full border bg-muted/40 px-3 py-1 text-xs font-medium text-muted-foreground">Step {index + 1} of {slides.length} · {slide.eyebrow}</span><h2 className="mt-4 max-w-xl text-[clamp(2rem,4.2vw,3.75rem)] font-semibold leading-[1.04] tracking-[-.04em] sm:mt-5">{slide.title}</h2><p className="mt-4 max-w-lg text-sm leading-6 text-muted-foreground sm:text-base sm:leading-7">{slide.description}</p><div className="mt-5 grid gap-2.5 sm:mt-6">{slide.points.map(point => <div className="flex items-center gap-3 text-sm font-medium" key={point}><span className="grid size-6 place-items-center rounded-full bg-primary/10 text-primary"><Check className="size-3.5"/></span>{point}</div>)}</div></div>
      <OnboardingVisual index={index}/>
    </div></CarouselItem>)}</CarouselContent><div className="mt-6 flex items-center justify-between gap-5"><div className="flex items-center gap-2" aria-label={`Tutorial step ${current + 1} of ${slides.length}`}>{slides.map((slide, index) => <button aria-label={`Go to ${slide.title}`} className={cn("h-1.5 rounded-full transition-all duration-300", index === current ? "w-10 bg-primary" : "w-4 bg-border hover:bg-muted-foreground/40")} key={slide.title} onClick={() => api?.scrollTo(index)} type="button"/>)}</div><div className="flex items-center gap-2"><CarouselPrevious className="static my-0"/><CarouselNext className="static my-0"/>{current === slides.length - 1 ? <Button onClick={finish}><CheckCircle2 data-icon="inline-start"/>Start using Litera</Button> : <Button onClick={() => api?.scrollNext()}>Continue<ArrowRight data-icon="inline-end"/></Button>}</div></div></Carousel>
  </DialogContent></Dialog>;
}

function OnboardingVisual({ index }: { index: number }) {
  return <div className="onboarding-demo relative min-h-[clamp(18rem,40dvh,31rem)] min-w-0 overflow-hidden rounded-[1.5rem] border bg-background text-foreground shadow-2xl shadow-foreground/10 sm:rounded-[2rem] lg:h-full" data-scene={index}>
    <div className="flex h-11 items-center justify-between border-b bg-card px-4"><div aria-label="Window controls" className="flex items-center gap-2"><span className="group grid size-3.5 place-items-center rounded-full bg-destructive text-destructive-foreground"><X className="size-2 opacity-0 group-hover:opacity-100"/></span><span className="group grid size-3.5 place-items-center rounded-full bg-warning text-foreground"><Minus className="size-2 opacity-0 group-hover:opacity-100"/></span><span className="group grid size-3.5 place-items-center rounded-full bg-success text-foreground"><Maximize2 className="size-1.5 opacity-0 group-hover:opacity-100"/></span></div><span className="rounded-full bg-muted px-2.5 py-1 text-[9px] text-muted-foreground">Interactive preview</span></div>
    <div className="grid h-[calc(100%-2.75rem)] grid-cols-[5.5rem_1fr] sm:grid-cols-[7rem_1fr]"><aside className="border-r bg-muted/25 p-2.5"><div className="mb-3 flex h-7 items-center justify-center gap-1 rounded-md bg-primary px-2 text-[8px] font-semibold text-primary-foreground"><FileUp className="size-3"/>New book</div><div className="grid gap-1.5">{["Mazingira", "Sayansi", "Historia"].map((book, item) => <div className={cn("truncate rounded-md px-2 py-2 text-[9px] text-muted-foreground", item === 0 && "bg-muted font-medium text-foreground")} key={book}>{book}</div>)}</div></aside><div className="relative min-w-0 overflow-hidden p-3 sm:p-4"><DemoScene index={index}/></div></div>
    <div className="demo-cursor absolute"><MousePointer2 className="size-6 fill-background text-foreground drop-shadow-md"/><span>Amina</span></div>
  </div>;
}

function DemoScene({ index }: { index: number }) {
  if (index === 0) return <div className="h-full"><p className="text-[9px] font-medium text-primary">LOCAL LIBRARY</p><h3 className="mt-1 text-sm font-semibold sm:text-base">Your books</h3><div className="demo-upload-target mt-4 grid min-h-28 place-items-center rounded-xl border border-dashed bg-muted/20 text-center"><div><UploadCloud className="mx-auto mb-2 size-6 text-primary"/><strong className="block text-[10px]">Import a source book</strong><span className="text-[8px] text-muted-foreground">PDF, EPUB, or project package</span></div></div><div className="demo-result mt-3 flex items-center gap-2 rounded-lg border bg-card p-2.5"><FileText className="size-4 text-primary"/><div><strong className="block text-[9px]">Mazingira yetu</strong><span className="text-[8px] text-muted-foreground">Ready to continue</span></div></div></div>;
  if (index === 1) return <div className="h-full"><p className="text-[9px] font-medium text-primary">MAZINGIRA YETU</p><h3 className="mt-1 text-sm font-semibold sm:text-base">Publishing pipeline</h3><div className="mt-4 grid grid-cols-2 gap-1.5 sm:grid-cols-4">{["Extract", "Structure", "Storyboard", "Speech"].map((stage, item) => <div className={cn("demo-stage rounded-lg border bg-card p-2", item === 2 && "demo-action-target")} key={stage}><span className="block text-[8px] text-muted-foreground">0{item + 1}</span><strong className="mt-3 block truncate text-[9px]">{stage}</strong></div>)}</div><div className="demo-panel mt-3 rounded-xl border bg-card p-3"><strong className="text-[10px]">Visual storyboard</strong><p className="mt-1 text-[8px] text-muted-foreground">Arrange pages and learning blocks.</p><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-muted"><span className="onboarding-demo-progress block h-full rounded-full bg-primary" style={{ "--demo-progress": "78%" } as React.CSSProperties}/></div></div></div>;
  if (index === 2) return <div className="h-full"><p className="text-[9px] font-medium text-primary">REOPEN PROJECT</p><h3 className="mt-1 text-sm font-semibold sm:text-base">Continue existing work</h3><div className="demo-upload-target mt-4 grid min-h-24 place-items-center rounded-xl border border-dashed bg-muted/20"><div className="text-center"><FileUp className="mx-auto mb-2 size-6 text-primary"/><strong className="block text-[10px]">Drop project package</strong></div></div><div className="demo-result mt-3 rounded-xl border bg-card p-3"><div className="flex items-center justify-between"><strong className="text-[10px]">Project recovered</strong><CheckCircle2 className="size-4 text-primary"/></div><div className="mt-3 grid grid-cols-4 gap-1">{[100, 100, 64, 0].map((value, item) => <div className="h-1.5 overflow-hidden rounded-full bg-muted" key={item}><span className="block h-full rounded-full bg-primary" style={{ width: `${value}%` }}/></div>)}</div></div></div>;
  if (index === 3) return <div className="h-full"><p className="text-[9px] font-medium text-primary">PROVIDER VAULT</p><h3 className="mt-1 text-sm font-semibold sm:text-base">Connect your provider</h3><div className="mt-4 grid gap-2">{["OpenAI API key", "Gemini API key", "Anthropic API key"].map((label, item) => <div className="rounded-lg border bg-card p-2.5" key={label}><span className="block text-[8px] text-muted-foreground">{label}</span><span className="mt-1.5 block h-2 w-3/4 rounded bg-muted">{item === 0 ? <span className="block h-full w-2/3 rounded bg-foreground/20"/> : null}</span></div>)}</div><button className="demo-action-target mt-3 w-full rounded-lg bg-primary py-2 text-[9px] font-semibold text-primary-foreground" type="button">Encrypt and save</button><div className="demo-result mt-2 text-center text-[8px] font-medium text-primary">Vault saved on this device</div></div>;
  return <div className="h-full"><p className="text-[9px] font-medium text-primary">FINAL REVIEW</p><h3 className="mt-1 text-sm font-semibold sm:text-base">Validate and export</h3><div className="mt-4 grid gap-2">{["Reading order", "Alternative text", "Narration timing"].map((check, item) => <div className="demo-check flex items-center gap-2 rounded-lg border bg-card p-2.5" key={check}><span className="grid size-4 place-items-center rounded-full border text-primary">{item < 2 ? <Check className="size-3"/> : null}</span><span className="text-[9px]">{check}</span></div>)}</div><button className="demo-action-target mt-3 w-full rounded-lg bg-primary py-2 text-[9px] font-semibold text-primary-foreground" type="button">Export publication</button><div className="demo-result mt-2 text-center text-[8px] font-medium text-primary">Publication ready</div></div>;
}

export function hasCompletedOnboarding() { return typeof window !== "undefined" && localStorage.getItem(onboardingKey) === "true"; }

export function HelpPage({ onBack, onTutorial }: { onBack: () => void; onTutorial: () => void }) {
  const topics = [
    { icon: FileUp, title: "Create or reopen a book", body: "Import a PDF to begin, or open an EPUB, Web Publication, or ZIP package to continue compatible existing work." },
    { icon: Layers3, title: "Work stage by stage", body: "Choose a colored pipeline stage. Completed work is preserved so corrections begin exactly where attention is needed." },
    { icon: KeyRound, title: "Configure AI providers", body: "Create a local vault password and add only the provider keys you intend to use. The password itself is never stored." },
    { icon: Video, title: "Assign signed videos", body: "Add local video files in the Sign language stage, then map each one to the relevant page, section, or phrase." },
    { icon: RefreshCw, title: "Keep Litera updated", body: "The top-bar update control verifies signed releases and becomes an installation action when a newer version exists." },
  ];
  return <section className="min-h-[calc(100vh-4rem)] bg-background"><div className="mx-auto max-w-7xl px-5 py-8 md:px-8 lg:py-12"><Button onClick={onBack} variant="ghost"><ArrowLeft data-icon="inline-start"/>Back to workspace</Button><div className="mt-8 grid gap-8 lg:grid-cols-[.72fr_1.28fr] lg:gap-14"><div className="lg:sticky lg:top-28 lg:self-start"><span className="grid size-12 place-items-center rounded-2xl bg-primary/10 text-primary"><HelpCircle/></span><h1 className="mt-6 text-4xl font-semibold tracking-tight sm:text-5xl">Help, without the guesswork.</h1><p className="mt-5 max-w-lg text-lg leading-8 text-muted-foreground">Learn the Litera workflow from import to accessible release, or replay the guided product tour.</p><Button className="mt-7" onClick={onTutorial}><Play data-icon="inline-start"/>Take the guided tour</Button></div><div className="grid gap-4">{topics.map((topic, index) => <Card className="motion-card" key={topic.title}><CardHeader><div className="flex items-start gap-4"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-muted text-primary"><topic.icon/></span><div><span className="font-mono text-xs text-primary">0{index + 1}</span><CardTitle className="mt-2">{topic.title}</CardTitle><CardDescription className="mt-2 max-w-2xl text-base leading-7">{topic.body}</CardDescription></div></div></CardHeader><CardContent><p className="text-sm text-muted-foreground">Open the relevant workspace stage to see contextual controls and progress.</p></CardContent></Card>)}</div></div></div></section>;
}
