import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, BookOpen, Mail, MessageCircle, Workflow } from "lucide-react";
import { PageHero } from "@/components/site/page-hero";
import { PageShell } from "@/components/site/page-shell";
import { ClosingCta } from "@/components/site/closing-cta";
import { FaqSection } from "@/components/site/faq-section";
import { VectorScene } from "@/components/site/vector-scene";
import { Button } from "@/components/ui/button";
import { Card, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";

export const metadata: Metadata = { title: "Contact", description: "Talk with the Litera team about accessible publishing, Swahili narration, and your learning workflow.", alternates: { canonical: "/contact" } };
export default function ContactPage() {
  return <PageShell><main>
    <PageHero eyebrow="Contact" title="Let’s make learning easier to reach." description="Tell us about the books, learners and publishing workflow your team needs to support." icon={MessageCircle}/>
    <section className="mx-auto max-w-6xl px-5 py-24 lg:px-8"><div className="grid gap-5 md:grid-cols-2"><Card><CardHeader className="p-8 sm:p-10"><Mail className="size-7 text-primary"/><CardTitle className="pt-5 text-2xl">Start a conversation</CardTitle><CardDescription className="text-base leading-7">Share the languages, formats and accessibility outcomes that matter to your learners. We’ll use them to shape a focused product conversation.</CardDescription><div className="pt-4"><Button asChild><Link href="/contact/email">Email the Litera team<ArrowRight/></Link></Button></div></CardHeader></Card><div className="grid gap-5"><Card className="motion-card"><CardHeader><BookOpen className="size-5 text-primary"/><CardTitle>Bring a real publication</CardTitle><CardDescription>Walk through a representative book or lesson so the discussion stays grounded.</CardDescription></CardHeader></Card><Card className="motion-card"><CardHeader><Workflow className="size-5 text-primary"/><CardTitle>Map your workflow</CardTitle><CardDescription>Show how authors, reviewers and stakeholders collaborate today and where work slows down.</CardDescription></CardHeader></Card></div></div></section>
    <section className="border-y bg-muted/30"><div className="mx-auto max-w-6xl px-5 py-20 text-center lg:px-8"><h2 className="text-3xl font-semibold tracking-tight">A useful first conversation</h2><p className="mx-auto mt-4 max-w-2xl leading-7 text-muted-foreground">Come ready with your content formats, required languages, publishing volume and accessibility goals. Those four details help us understand the shape of your work.</p></div></section>
    <section className="mx-auto grid max-w-6xl gap-14 px-5 py-24 lg:grid-cols-2 lg:items-center lg:px-8" data-reveal><div><p className="text-sm font-semibold uppercase tracking-[.2em] text-primary">What happens next</p><h2 className="mt-4 text-4xl font-semibold tracking-tight">A practical conversation, not a generic pitch.</h2><p className="mt-5 leading-8 text-muted-foreground">We begin with a real publication and the people responsible for it. Together, we map the current path, identify the most costly handoffs and define what a better learner outcome looks like.</p><ol className="mt-8 grid gap-3">{[["01","Share the context"],["02","Walk through the workflow"],["03","Identify the right next step"]].map(([n,label])=><li className="flex items-center gap-4 rounded-xl border p-4" key={label}><span className="font-mono text-xs text-primary">{n}</span><span className="font-medium">{label}</span></li>)}</ol></div><VectorScene variant="compose"/></section>
    <section className="border-y bg-muted/30" data-reveal><div className="mx-auto max-w-6xl px-5 py-24 lg:px-8"><div className="grid gap-5 md:grid-cols-3">{[["Content","Formats, volume and source quality"],["People","Authors, reviewers and approvers"],["Reach","Languages, devices and access needs"]].map(([title,text])=><Card className="motion-card" key={title}><CardHeader><CardTitle>{title}</CardTitle><CardDescription className="leading-7">{text}</CardDescription></CardHeader></Card>)}</div></div></section>
    <FaqSection title="Before you reach out." items={[["What should I include in my message?","Tell us what you publish, who contributes, which languages matter and where the current process becomes difficult."],["Can we discuss a specific publication?","Yes. A representative title or lesson is the best way to ground the conversation in real needs."],["Is Litera suitable for a multidisciplinary team?","Yes. The workspace is designed for creators, language reviewers, accessibility specialists, stakeholders and administrators."],["Where is the team based?","Litera is being developed from Dar es Salaam, Tanzania, with East African publishing realities at its centre."]]}/>
    <ClosingCta title="Your next accessible publication can begin with one message." description="Share the context and we’ll help turn it into a clear, practical publishing journey."/>
  </main></PageShell>;
}
